const fs = require('fs');
console.log('Running switch-db.js script...');
const path = require('path');

const schemaPath = path.join(__dirname, '..', 'prisma', 'schema.prisma');
const configPath = path.join(__dirname, '..', 'src', 'lib', 'db-config.ts');
const type = process.argv[2];

if (!fs.existsSync(schemaPath)) {
  console.error('Schema file not found at:', schemaPath);
  process.exit(1);
}

let schema = fs.readFileSync(schemaPath, 'utf8');

// Regex to match the datasource block
const datasourceRegex = /datasource db \{[\s\S]*?\}/;

if (type === 'postgres') {
  // Replace the datasource block with PostgreSQL configuration
  schema = schema.replace(
    datasourceRegex,
    `datasource db {
  provider = "postgresql"
}`
  );
  
  // Write config file
  fs.writeFileSync(configPath, `// Auto-generated by scripts/switch-db.js
export const dbType = 'postgres';
`);
  
  console.log('✔ Switched Prisma schema to PostgreSQL');
  console.log('✔ Generated db-config.ts for PostgreSQL');
  
} else if (type === 'sqlite') {
  // Replace the datasource block with SQLite configuration
  schema = schema.replace(
    datasourceRegex,
    `datasource db {
  provider = "sqlite"
}`
  );
  
  // Write config file
  fs.writeFileSync(configPath, `// Auto-generated by scripts/switch-db.js
export const dbType = 'sqlite';
`);

  console.log('✔ Switched Prisma schema to SQLite');
  console.log('✔ Generated db-config.ts for SQLite');
  
} else {
  console.error('Usage: node scripts/switch-db.js [postgres|sqlite]');
  process.exit(1);
}

fs.writeFileSync(schemaPath, schema);
